# Generated by Django 5.1.7 on 2025-03-30 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pacientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='direccion',
            new_name='historial_medico',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='telefono',
        ),
        migrations.AddField(
            model_name='paciente',
            name='usuario',
            field=models.OneToOneField(default=101, on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_doctor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_paciente',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='doctor',
            table='gestion_pacientes_doctor',
        ),
        migrations.AlterModelTable(
            name='paciente',
            table='gestion_pacientes_paciente',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='gestion_pacientes_usuario',
        ),
    ]
