# Generated by Django 5.1.7 on 2025-03-30 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pacientes', '0002_rename_direccion_paciente_historial_medico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='años_experiencia',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='especialidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='numero_licencia',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
