# Generated by Django 5.1.7 on 2025-04-19 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pacientes', '0004_cita_historiaclinica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='especialidad',
            field=models.CharField(choices=[('medicina general', 'Medicina General'), ('ginecologia', 'ginecologia'), ('psicologia', 'Psicologia'), ('odontologia', 'Odontologia'), ('planificacion familiar', 'Planificacion Familiar'), ('pediatria', 'Pediatria')], default='medicina general', max_length=50),
        ),
    ]
