# Generated by Django 5.1.7 on 2025-04-19 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pacientes', '0005_alter_doctor_especialidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='horario_atencion',
        ),
        migrations.AddField(
            model_name='doctor',
            name='fin_horario',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='inicio_horario',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
