# Generated by Django 5.1.7 on 2025-04-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pacientes', '0006_remove_doctor_horario_atencion_doctor_fin_horario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='historial_medico',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='especialidad',
            field=models.CharField(choices=[('Medicina general', 'Medicina General'), ('Ginecologia', 'Ginecologia'), ('Psicologia', 'Psicologia'), ('Odontologia', 'Odontologia'), ('Planificacion familiar', 'Planificacion Familiar'), ('Pediatria', 'Pediatria')], default='Medicina general', max_length=50),
        ),
    ]
